name: Build Fabric Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Ensure Gradle wrapper is executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # 4️⃣ Optional: verify Gradle version (wrapper must be 8.3)
      - name: Check Gradle version
        run: ./gradlew --version

      # 5️⃣ Build the mod (refresh dependencies to avoid cached JSON issues)
      - name: Build Mod
        run: ./gradlew build --no-daemon --refresh-dependencies

      # 6️⃣ Upload the built JAR
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beer-mod-jar
          path: build/libs/beer-0.1.0.jar

      # 6️⃣ Create GitHub Release and attach JAR
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "Beer Mod v${{ github.run_number }}"
          body: "Automated release from GitHub Actions"
          artifacts: build/libs/beer-0.1.0.jar
          draft: false
          prerelease: false
