name: Build and Release Fabric Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Check current Java version
      - name: Check Current Java Version
        run: |
          echo "Current Java:"
          java -version || true

      # 3️⃣ Set up Java 17 if not already set
      - name: Ensure Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 4️⃣ Confirm Java 17 is being used
      - name: Verify Java 17
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          javac -version

      # 5️⃣ Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # 6️⃣ Build the mod with fresh dependencies
      - name: Build Mod
        run: ./gradlew build --no-daemon --refresh-dependencies

      # 7️⃣ Upload the JAR as artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beer-mod-jar
          path: build/libs/beer-0.1.0.jar

      # 8️⃣ Create GitHub Release with the mod JAR
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "Beer Mod v${{ github.run_number }}"
          body: "Automated release from GitHub Actions"
          artifacts: build/libs/beer-0.1.0.jar
          draft: false
          prerelease: false
