name: Build Fabric Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Install Gradle 8.3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.3

      # 4️⃣ Build the mod
      - name: Build Mod
        run: gradle build --no-daemon

      # 5️⃣ Upload the compiled JAR
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beer-mod-jar
          path: build/libs/beer-0.1.0.jar
